# Generated by Django 4.2.9 on 2024-04-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=200)),
                ('Phone', models.TextField(max_length=1200)),
                ('Message', models.CharField(max_length=1200)),
            ],
            options={
                'verbose_name': 'Contact Us Page',
                'db_table': 'Contact_List',
            },
        ),
    ]
