# Generated by Django 4.2.9 on 2024-04-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactPage', '0002_alter_contactform_options_alter_contactform_message_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Contact_List',
        ),
    ]
