# Generated by Django 4.2.9 on 2024-04-08 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_movie',
            options={'verbose_name': 'Add Movie'},
        ),
    ]
