# Generated by Django 4.2.9 on 2024-04-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_alter_add_movie_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_movie',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
